#!/usr/bin/env -S npx tsx
// Milestone 5 step 3 — same signing scheme as sign.ts (see that file's
// header for the message-to-curve caveat: simplified, NOT Ethereum's real
// RFC9380/SSZ signing_root — that's a separate, later step), generalized to
// an arbitrary committee size N and a `bytes` participant bitmap (SSZ
// Bitvector[N] bit order: bit i lives at byte i/8, bit i%8 — LSB first)
// instead of sign.ts's `uint256` bitmap, which can't address more than 256
// validators. Used by contracts/test/LightClientVerifierBLSGeneral.t.sol
// via `vm.ffi` against a committee generated by generate_keys_general.ts.
//
// Usage: npx tsx sign_general.ts <keysJsonPath> <chainId> <blockNumber> <stateRoot> <participantCount>
//   Signs with validators [0, participantCount) — a simple deterministic
//   subset, sufficient for exercising threshold boundaries (exactly at
//   threshold, threshold-1, all N, etc.) without needing arbitrary subsets.

import fs from "fs";
import { bls12_381 } from "@noble/curves/bls12-381.js";
import { ethers } from "ethers";

const [, , keysJsonPath, chainIdArg, blockNumberArg, stateRootArg, participantCountArg] = process.argv;
if (!keysJsonPath || !chainIdArg || !blockNumberArg || !stateRootArg || !participantCountArg) {
  console.error("usage: sign_general.ts <keysJsonPath> <chainId> <blockNumber> <stateRoot> <participantCount>");
  process.exit(1);
}

const keys = JSON.parse(fs.readFileSync(keysJsonPath, "utf8")) as {
  numValidators: number;
  validators: { secretKey: string }[];
};
const participantCount = Number(participantCountArg);
if (participantCount < 0 || participantCount > keys.numValidators) {
  throw new Error(`participantCount ${participantCount} out of range [0, ${keys.numValidators}]`);
}

function fpHex(n: bigint): string {
  return n.toString(16).padStart(128, "0");
}

function g2Hex(point: { toAffine?: () => any } & Record<string, any>): string {
  const p = point.toAffine ? point.toAffine() : point;
  return "0x" + fpHex(p.x.c0) + fpHex(p.x.c1) + fpHex(p.y.c0) + fpHex(p.y.c1);
}

/// Mirrors LightClientVerifierBLS(General).sol::_hashToG2 exactly — same
/// simplified (non-RFC9380) message-to-curve as sign.ts.
function messagePoint(chainId: bigint, blockNumber: bigint, stateRoot: bigint) {
  const u0 = BigInt(
    ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(["string", "uint256", "uint256", "uint256"], ["BLS_MSG_U0", chainId, blockNumber, stateRoot]))
  );
  const u1 = BigInt(
    ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(["string", "uint256", "uint256", "uint256"], ["BLS_MSG_U1", chainId, blockNumber, stateRoot]))
  );
  return bls12_381.G2.mapToCurve([u0, u1]) as unknown as InstanceType<typeof bls12_381.G2.Point>;
}

/// SSZ Bitvector[N]-compatible encoding: bit i -> byte i>>3, bit i&7 (LSB
/// first within each byte) — same convention sync_committee_probe.ts reads
/// from real Ethereum data, so this bitmap format is forward-compatible
/// with real sync_committee_bits once Milestone 5 gets that far.
function encodeBitmap(numValidators: number, participating: (i: number) => boolean): string {
  const numBytes = Math.ceil(numValidators / 8);
  const bytes = new Uint8Array(numBytes);
  for (let i = 0; i < numValidators; i++) {
    if (participating(i)) bytes[i >> 3]! |= 1 << (i & 7);
  }
  return "0x" + Buffer.from(bytes).toString("hex");
}

const chainId = BigInt(chainIdArg);
const blockNumber = BigInt(blockNumberArg);
const stateRoot = BigInt(stateRootArg);

const M = messagePoint(chainId, blockNumber, stateRoot);

let aggSig: ReturnType<typeof M.multiply> | null = null;
for (let i = 0; i < participantCount; i++) {
  const scalar = BigInt(keys.validators[i]!.secretKey);
  const sig = M.multiply(scalar);
  aggSig = aggSig === null ? sig : aggSig.add(sig);
}

const participantBitmap = encodeBitmap(keys.numValidators, (i) => i < participantCount);

if (aggSig === null) {
  // participantCount == 0 — no valid curve point to encode; caller (test)
  // is expected to be testing the "insufficient quorum" revert path and
  // won't use aggSig in that case, but still needs a well-formed bitmap.
  console.log(JSON.stringify({ aggSig: null, participantBitmap }));
} else {
  console.log(JSON.stringify({ aggSig: g2Hex(aggSig), participantBitmap }));
}
