// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {LightClientVerifierBLS} from "../src/LightClientVerifierBLS.sol";

/// @notice Exercises LightClientVerifierBLS.sol with REAL BLS12-381
///         aggregate signatures generated by bls-validators/sign.js (via
///         `vm.ffi`) — same pattern as ChannelStateProof.t.sol's real ZK
///         proofs, LightClient.t.sol's real consensus proofs, etc.
contract LightClientVerifierBLSTest is Test {
    LightClientVerifierBLS lightClient;

    uint256 constant CHAIN_ID = 31337;

    function setUp() public {
        lightClient = new LightClientVerifierBLS();
    }

    function _sign(uint256 chainId, uint256 blockNumber, uint256 stateRoot, uint256 participantBitmap)
        internal
        returns (bytes memory aggSig)
    {
        string[] memory cmd = new string[](6);
        cmd[0] = "node";
        cmd[1] = "../bls-validators/sign.js";
        cmd[2] = vm.toString(chainId);
        cmd[3] = vm.toString(blockNumber);
        cmd[4] = vm.toString(stateRoot);
        cmd[5] = vm.toString(participantBitmap);

        bytes memory result = vm.ffi(cmd);
        string memory json = string(result);
        aggSig = vm.parseJsonBytes(json, ".aggSig");
    }

    function test_updateState_acceptsRealQuorumSignature() public {
        uint256 participantBitmap = 0x07; // validators 0,1,2 — exactly THRESHOLD
        bytes memory aggSig = _sign(CHAIN_ID, 1, 12345, participantBitmap);

        lightClient.updateState(CHAIN_ID, 1, 12345, participantBitmap, aggSig);

        assertEq(lightClient.trustedStateRoot(CHAIN_ID), 12345);
        assertEq(lightClient.trustedBlockNumber(CHAIN_ID), 1);
    }

    function test_updateState_acceptsDifferentQuorumSubset() public {
        // Validators 1,3,4 instead of 0,1,2 — the point-addition aggregation
        // must be order/subset-independent, and each validator's real
        // scalar-multiplied signature must combine correctly.
        uint256 participantBitmap = (1 << 1) | (1 << 3) | (1 << 4);
        bytes memory aggSig = _sign(CHAIN_ID, 1, 999, participantBitmap);

        lightClient.updateState(CHAIN_ID, 1, 999, participantBitmap, aggSig);

        assertEq(lightClient.trustedStateRoot(CHAIN_ID), 999);
    }

    function test_updateState_revertsBelowThreshold() public {
        uint256 participantBitmap = 0x03; // only validators 0,1 — below THRESHOLD=3
        bytes memory aggSig = _sign(CHAIN_ID, 1, 12345, participantBitmap);

        vm.expectRevert(LightClientVerifierBLS.InsufficientQuorum.selector);
        lightClient.updateState(CHAIN_ID, 1, 12345, participantBitmap, aggSig);
    }

    function test_updateState_revertsOnTamperedStateRoot() public {
        uint256 participantBitmap = 0x07;
        bytes memory aggSig = _sign(CHAIN_ID, 1, 12345, participantBitmap);

        // Claim a DIFFERENT stateRoot than what was actually signed.
        vm.expectRevert(LightClientVerifierBLS.InvalidAggregateSignature.selector);
        lightClient.updateState(CHAIN_ID, 1, 99999, participantBitmap, aggSig);
    }

    function test_updateState_revertsOnStaleBlockNumber() public {
        uint256 participantBitmap = 0x07;
        bytes memory aggSig1 = _sign(CHAIN_ID, 5, 111, participantBitmap);
        lightClient.updateState(CHAIN_ID, 5, 111, participantBitmap, aggSig1);

        bytes memory aggSig2 = _sign(CHAIN_ID, 5, 222, participantBitmap);
        vm.expectRevert(LightClientVerifierBLS.StaleBlockNumber.selector);
        lightClient.updateState(CHAIN_ID, 5, 222, participantBitmap, aggSig2);
    }

    function test_updateState_revertsWhenSignedByFewerValidatorsThanClaimed() public {
        // Claim bitmap {0,1,2} in the CALL, but the signature was only
        // actually produced by {0,1} — the on-chain aggregate pubkey (built
        // from the CLAIMED bitmap) won't match the real signers.
        bytes memory aggSig = _sign(CHAIN_ID, 1, 12345, 0x03); // signed by 0,1 only

        vm.expectRevert(LightClientVerifierBLS.InvalidAggregateSignature.selector);
        lightClient.updateState(CHAIN_ID, 1, 12345, 0x07, aggSig); // claims 0,1,2
    }
}
