//! End-to-end MockProver check for `ChannelStateCircuit`, using a REAL
//! witness generated by circomlibjs (same DEFAULT_PRIV_KEY_A/B as
//! circuits/input_gen/build_channel_state_input.js) — see
//! circuits-halo2/README.md for the exact generation command. This is the
//! decisive correctness check: MockProver evaluates every gate over every
//! row and reports exactly which constraint fails, if any.

#[cfg(test)]
mod tests {
    use crate::circuit::{ChannelStateCircuit, SignatureWitness};
    use halo2_proofs::dev::MockProver;
    use halo2curves::bn256::Fr;
    use halo2curves::ff::PrimeField;

    fn fr(s: &str) -> Fr {
        Fr::from_str_vartime(s).expect("valid decimal Fr")
    }

    fn real_witness_circuit() -> ChannelStateCircuit {
        // Generated via circomlibjs — see circuits-halo2/README.md. Same
        // domain separator formula as channel_state.circom: Poseidon7
        // (contractAddress, chainId, channelId, nonce, balanceA, balanceB).
        ChannelStateCircuit {
            contract_address: fr("97433442488726861213578988847752201310395502865"),
            chain_id: Fr::from(31337u64),
            channel_id: Fr::from(1u64),
            nonce: Fr::from(1u64),
            balance_a: Fr::from(400000u64),
            balance_b: Fr::from(600000u64),
            total_deposit: Fr::from(1000000u64),
            pub_key_ax: fr("6258698228857579243937097735069405513777546488206385948349971781708128047847"),
            pub_key_ay: fr("2216124967747932654884761600749314631961003421499958761754620989171020525870"),
            pub_key_bx: fr("21036738825193802266623779881692904721121294284483365787352024792419651640674"),
            pub_key_by: fr("17088268747125489648041885901336523179405935374090472533134592214513880559267"),
            sig_a: SignatureWitness {
                r8x: fr("4917344699118670943373348864095189513110544881241303759698448356854879866857"),
                r8y: fr("5468544676196101173266500702471328966306068888220567829875945479129822096316"),
                s: fr("2332341740213430710895160059533639433920566388022543560963322443715774995966"),
            },
            sig_b: SignatureWitness {
                r8x: fr("8425486573857761199328174831877931532857805810054432862926891341132244559543"),
                r8y: fr("14076165714719029565373764552193210300296476170884431308989492567248263735781"),
                s: fr("1013225836428401173556310194350073290416509558752576451792834375459276379446"),
            },
        }
    }

    #[test]
    fn message_hash_matches_circomlibjs() {
        let circuit = real_witness_circuit();
        // messageHash from circomlibjs: poseidon([contractAddress, chainId, channelId, nonce, balanceA, balanceB])
        assert_eq!(circuit.message_hash(), fr("7320757441107426998486439317962418263474361961181607439992948532301834320754"));
    }

    #[test]
    fn valid_witness_satisfies_all_constraints() {
        let circuit = real_witness_circuit();
        let public_inputs = circuit.public_inputs();

        let k = 17; // circuit size parameter (2^k rows) — see README for how this was picked
        let prover = MockProver::run(k, &circuit, vec![public_inputs]).expect("MockProver setup must succeed");
        prover.verify().expect("a genuinely valid witness must satisfy every constraint");
    }

    #[test]
    fn tampered_signature_is_rejected() {
        let mut circuit = real_witness_circuit();
        circuit.sig_a.s += Fr::one(); // tamper with partyA's signature
        let public_inputs = circuit.public_inputs();

        let k = 17;
        let prover = MockProver::run(k, &circuit, vec![public_inputs]).expect("MockProver setup must succeed");
        assert!(prover.verify().is_err(), "a tampered signature must NOT satisfy the constraints");
    }

    #[test]
    fn violated_conservation_is_rejected() {
        let mut circuit = real_witness_circuit();
        circuit.balance_a += Fr::one(); // balanceA + balanceB != totalDeposit now
        let public_inputs = circuit.public_inputs();

        let k = 17;
        let prover = MockProver::run(k, &circuit, vec![public_inputs]).expect("MockProver setup must succeed");
        assert!(prover.verify().is_err(), "violating conservation must NOT satisfy the constraints");
    }
}
