//! End-to-end MockProver check for `ChannelStateCircuit`, using a REAL
//! 4-step witness generated by circomlibjs (same DEFAULT_PRIV_KEY_A/B as
//! circuits/input_gen/build_channel_state_input.js) — see
//! circuits-halo2/README.md for the exact generation command. This is the
//! decisive correctness check: MockProver evaluates every gate over every
//! row and reports exactly which constraint fails, if any.

#[cfg(test)]
mod tests {
    use crate::circuit::demo_witness;
    use halo2_proofs::dev::MockProver;
    use halo2curves::bn256::Fr;
    use halo2curves::ff::PrimeField;

    fn fr(s: &str) -> Fr {
        Fr::from_str_vartime(s).expect("valid decimal Fr")
    }

    #[test]
    fn message_hash_matches_circomlibjs() {
        let circuit = demo_witness();
        // messageHash[0] from circomlibjs: poseidon([contractAddress, chainId, channelId, nonce[0]=1, balanceA[0]=400000, balanceB[0]=600000])
        // — same inputs as the original single-step reference test, so the
        // expected value carries over unchanged.
        assert_eq!(circuit.message_hash_at(0), fr("7320757441107426998486439317962418263474361961181607439992948532301834320754"));
    }

    #[test]
    fn valid_witness_satisfies_all_constraints() {
        let circuit = demo_witness();
        let public_inputs = circuit.public_inputs();

        let k = 19; // circuit size parameter (2^k rows) — 4x the rows of the original 1-step reference (STEPS=4 now); see README
        let prover = MockProver::run(k, &circuit, vec![public_inputs]).expect("MockProver setup must succeed");
        prover.verify().expect("a genuinely valid witness must satisfy every constraint");
    }

    #[test]
    fn tampered_signature_is_rejected() {
        let mut circuit = demo_witness();
        circuit.sig_a[1].s += Fr::one(); // tamper with partyA's signature on step 1
        let public_inputs = circuit.public_inputs();

        let k = 19;
        let prover = MockProver::run(k, &circuit, vec![public_inputs]).expect("MockProver setup must succeed");
        assert!(prover.verify().is_err(), "a tampered signature must NOT satisfy the constraints");
    }

    #[test]
    fn violated_conservation_is_rejected() {
        let mut circuit = demo_witness();
        circuit.balance_a[2] += Fr::one(); // balanceA[2] + balanceB[2] != totalDeposit now
        let public_inputs = circuit.public_inputs();

        let k = 19;
        let prover = MockProver::run(k, &circuit, vec![public_inputs]).expect("MockProver setup must succeed");
        assert!(prover.verify().is_err(), "violating conservation must NOT satisfy the constraints");
    }

    #[test]
    fn non_increasing_nonce_is_rejected() {
        let mut circuit = demo_witness();
        // Step 2's nonce (3) dropped to equal step 1's (2) — must fail the
        // strictly-increasing check even though every signature and
        // conservation check individually still passes.
        circuit.nonce[2] = circuit.nonce[1];
        let public_inputs = circuit.public_inputs();

        let k = 19;
        let prover = MockProver::run(k, &circuit, vec![public_inputs]).expect("MockProver setup must succeed");
        assert!(prover.verify().is_err(), "a non-increasing nonce must NOT satisfy the constraints");
    }

    #[test]
    fn wrong_claimed_final_state_is_rejected() {
        let mut circuit = demo_witness();
        // outNonce claims 5, but the witness's actual last step is nonce 4.
        circuit.out_nonce = Fr::from(5u64);
        let public_inputs = circuit.public_inputs();

        let k = 19;
        let prover = MockProver::run(k, &circuit, vec![public_inputs]).expect("MockProver setup must succeed");
        assert!(prover.verify().is_err(), "a final state not matching the witnessed chain must NOT satisfy the constraints");
    }
}
