// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title BabyJubJub
/// @notice Minimal point arithmetic on the Baby Jubjub twisted Edwards curve
///         (a*x^2 + y^2 = 1 + d*x^2*y^2 mod Q) — the curve circomlib's EdDSA
///         implementation (and therefore `channel_state.circom`) uses for
///         parties' off-chain signing keys.
///
///         This is NOT a general EdDSA-Poseidon verifier — that stays inside
///         the circuit, where Poseidon is cheap. Poseidon is expensive as
///         plain EVM opcodes, so `PaymentChannel._verifyKeyOwnership` instead
///         checks a plain Schnorr signature over this same curve/keypair with
///         a keccak256 Fiat-Shamir challenge (native to the EVM). See
///         `circuits/input_gen/eddsa_ownership.js` for the off-chain half.
///
///         Scalar multiplication and point addition are done in projective
///         (X:Y:Z) coordinates ("add-2008-bbjlp" / "dbl-2008-bbjlp" from the
///         Explicit-Formulas Database, general a/d), which need only field
///         multiplications — no modular inverse — per group operation. Only
///         the final X/Z, Y/Z conversion back to affine needs one. An earlier
///         affine-only version of this library called the modexp precompile
///         twice per point op (~500+ calls, ~5-10M gas for one Schnorr
///         verify); this version calls it 2-3 times total per verify.
library BabyJubJub {
    // Base field of BN254/alt_bn128 — the field Baby Jubjub is defined over.
    uint256 internal constant Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 internal constant A_COEFF = 168700;
    uint256 internal constant D_COEFF = 168696;

    // Order of the prime-order subgroup generated by BASE8 (circomlib's `subOrder`).
    uint256 internal constant SUB_ORDER = 2736030358979909402780800718157159386076813972158567259200215660948447373041;

    // Generator circomlib's EdDSA uses (`Base8`, i.e. 8 * the curve's actual generator).
    uint256 internal constant BASE8_X = 5299619240641551281634865583518297030282874472190772894086521144482721001553;
    uint256 internal constant BASE8_Y = 16950150798460657717958625567821834550301663161624707787222815936182638968203;

    /// @dev Modular inverse mod Q via Fermat's little theorem (Q is prime),
    ///      using the modexp precompile (0x05) instead of a Solidity loop.
    function invmod(uint256 x) internal view returns (uint256) {
        return expmod(x, Q - 2, Q);
    }

    function expmod(uint256 base, uint256 exponent, uint256 modulus) internal view returns (uint256 result) {
        assembly {
            let ptr := mload(0x40)
            mstore(ptr, 0x20)
            mstore(add(ptr, 0x20), 0x20)
            mstore(add(ptr, 0x40), 0x20)
            mstore(add(ptr, 0x60), base)
            mstore(add(ptr, 0x80), exponent)
            mstore(add(ptr, 0xa0), modulus)
            if iszero(staticcall(gas(), 0x05, ptr, 0xc0, ptr, 0x20)) { revert(0, 0) }
            result := mload(ptr)
        }
    }

    /// @dev Projective unified addition — correct for P+Q, P+P (doubling would
    ///      also work here but `projDouble` is cheaper), and the identity
    ///      (0:1:1). No inversions. "add-2008-bbjlp", general a/d:
    ///      A=Z1*Z2 B=A^2 C=X1*X2 D=Y1*Y2 E=d*C*D F=B-E G=B+E
    ///      X3=A*F*((X1+Y1)(X2+Y2)-C-D)  Y3=A*G*(D-a*C)  Z3=F*G
    function projAdd(uint256 x1, uint256 y1, uint256 z1, uint256 x2, uint256 y2, uint256 z2)
        internal
        pure
        returns (uint256 x3, uint256 y3, uint256 z3)
    {
        uint256 a = mulmod(z1, z2, Q);
        uint256 b = mulmod(a, a, Q);
        uint256 c = mulmod(x1, x2, Q);
        uint256 d = mulmod(y1, y2, Q);
        uint256 e = mulmod(D_COEFF, mulmod(c, d, Q), Q);
        uint256 f = addmod(b, Q - e, Q);
        uint256 g = addmod(b, e, Q);
        uint256 t = addmod(mulmod(addmod(x1, y1, Q), addmod(x2, y2, Q), Q), Q - addmod(c, d, Q), Q);

        x3 = mulmod(mulmod(a, f, Q), t, Q);
        y3 = mulmod(mulmod(a, g, Q), addmod(d, Q - mulmod(A_COEFF, c, Q), Q), Q);
        z3 = mulmod(f, g, Q);
    }

    /// @dev Projective doubling. No inversions. "dbl-2008-bbjlp", general a:
    ///      B=(X1+Y1)^2 C=X1^2 D=Y1^2 E=a*C F=E+D H=Z1^2 J=F-2*H
    ///      X3=(B-C-D)*J  Y3=F*(E-D)  Z3=F*J
    function projDouble(uint256 x1, uint256 y1, uint256 z1) internal pure returns (uint256 x3, uint256 y3, uint256 z3) {
        uint256 b = mulmod(addmod(x1, y1, Q), addmod(x1, y1, Q), Q);
        uint256 c = mulmod(x1, x1, Q);
        uint256 d = mulmod(y1, y1, Q);
        uint256 e = mulmod(A_COEFF, c, Q);
        uint256 f = addmod(e, d, Q);
        uint256 h = mulmod(z1, z1, Q);
        uint256 j = addmod(f, Q - addmod(h, h, Q), Q);

        x3 = mulmod(addmod(b, Q - addmod(c, d, Q), Q), j, Q);
        y3 = mulmod(f, addmod(e, Q - d, Q), Q);
        z3 = mulmod(f, j, Q);
    }

    /// @dev Converts (X:Y:Z) back to affine (X/Z, Y/Z) — the one modexp call
    ///      per point this library needs.
    function toAffine(uint256 x, uint256 y, uint256 z) internal view returns (uint256 ax, uint256 ay) {
        uint256 zInv = invmod(z);
        ax = mulmod(x, zInv, Q);
        ay = mulmod(y, zInv, Q);
    }

    /// @notice Affine point addition — for combining two already-affine
    ///         points (e.g. `R8 + c*A` in `PaymentChannel._verifyKeyOwnership`).
    ///         One modexp call (the final `toAffine`).
    function pointAdd(uint256 x1, uint256 y1, uint256 x2, uint256 y2) internal view returns (uint256 x3, uint256 y3) {
        (uint256 px, uint256 py, uint256 pz) = projAdd(x1, y1, 1, x2, y2, 1);
        (x3, y3) = toAffine(px, py, pz);
    }

    /// @notice Scalar multiplication via a 4-bit windowed method, in
    ///         projective coordinates — one modexp call total (the final
    ///         `toAffine`), regardless of `scalar`'s bit length.
    /// @dev Builds a table of {0,1,2,...,15}*P (15 additions), then processes
    ///      `scalar` 4 bits (1 nibble) at a time from the top: 4 doublings +
    ///      1 addition per nibble, instead of naive double-and-add's up to 1
    ///      addition per BIT. Doublings are unchanged (still ~1 per bit —
    ///      windowing doesn't reduce those), but additions drop from up to
    ///      256 to a fixed 15 (table) + 64 (main loop) = 79 — the dominant
    ///      win, since building the table's ~identical formula cost is
    ///      amortized across all 64 windows. Table index 0 is the identity,
    ///      so every window always performs exactly one addition (adding the
    ///      identity for a zero nibble is a no-op under the complete
    ///      formulas above) — branch-free, not for constant-time-security
    ///      reasons (this scalar is never secret here, see
    ///      `PaymentChannel._verifyKeyOwnership`) but because it keeps the
    ///      loop uniform and simple.
    function mulScalar(uint256 x, uint256 y, uint256 scalar) internal view returns (uint256 rx, uint256 ry) {
        // table[i] = i*(x,y,1), projective, i in [0,15]
        uint256[16] memory tblX;
        uint256[16] memory tblY;
        uint256[16] memory tblZ;
        tblX[0] = 0;
        tblY[0] = 1;
        tblZ[0] = 1; // identity
        tblX[1] = x;
        tblY[1] = y;
        tblZ[1] = 1;
        for (uint256 i = 2; i < 16; i++) {
            (tblX[i], tblY[i], tblZ[i]) = projAdd(tblX[i - 1], tblY[i - 1], tblZ[i - 1], x, y, 1);
        }

        uint256 accX = 0;
        uint256 accY = 1;
        uint256 accZ = 1; // identity, projective

        for (uint256 w = 0; w < 64; w++) {
            // 4 doublings per window, except the very first (accumulator
            // still the identity — doubling it is a no-op but wasted gas).
            if (w != 0) {
                for (uint256 k = 0; k < 4; k++) {
                    (accX, accY, accZ) = projDouble(accX, accY, accZ);
                }
            }
            uint256 nibble = (scalar >> (252 - w * 4)) & 0xF;
            (accX, accY, accZ) = projAdd(accX, accY, accZ, tblX[nibble], tblY[nibble], tblZ[nibble]);
        }

        (rx, ry) = toAffine(accX, accY, accZ);
    }

    function isOnCurve(uint256 x, uint256 y) internal pure returns (bool) {
        if (x >= Q || y >= Q) return false;
        uint256 x2 = mulmod(x, x, Q);
        uint256 y2 = mulmod(y, y, Q);
        uint256 lhs = addmod(mulmod(A_COEFF, x2, Q), y2, Q);
        uint256 rhs = addmod(1, mulmod(D_COEFF, mulmod(x2, y2, Q), Q), Q);
        return lhs == rhs;
    }
}
